name = "roofing-co"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"
pages_functions_dir = "functions"

[build]
command = "npm run build"

[env.production]
name = "roofing-co"
route = "roofing-co-with-workers.pages.dev/*"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "auth-db"
database_id = "bef1c7fa-8bbd-4067-b293-b2dae6132680"

[[r2_buckets]]
binding = "ROOFING_CONFIGS"
bucket_name = "roofing-configs"
